### ISSUE TITLE
Remove `phonenumbers` import from top of PhoneNumberField

### ISSUE THREAD

**Issue by hjc1710** [croscon/fleaker#23]
Currently, in the `PhoneNumberField` module we are importing `phonenumbers` at the top of the module. This prevents the field from working if `phonenumbers` isn't installed, but it also prevents the documentation from generating. If we replace the `phonenumbers` failed import with an unbound `LocalProxy`, then we can still get the same error, but generate docs without `phonenumbers`.

Context here: https://github.com/croscon/fleaker/pull/21#discussion_r91964342

**Comment by eligundry** [comment]
This is closed cause we aren't playing around with `extras_requires`.
