### ISSUE TITLE
Custom Test Class for Fleaker

### ISSUE THREAD

**Issue by hjc1710** [croscon/fleaker#31]
There should definitely be a composable app mixin that defines a custom test client for Fleaker. A great example of what this can do, is set the test client up so that you can give a `json` kwarg a dict, and it will serialize that to json and add the appropriate headers.

Here's what I'm thinking:

* A good sample `TestClient` is this:
    ```python
     class TestClient(FlaskClient):
         """Custom Flask test client that will do magical things."""
     
         def open(self, *args, **kwargs):
             if 'json' in kwargs:
                 kwargs['data'] = flask.json.dumps(kwargs.pop('json'))
                 kwargs['content_type'] = 'application/json'
     
             return super(TestClient, self).open(*args, **kwargs)
    ```
    This overrides the `open` method to enable the usage of a `json` kwarg, as mentioned above.
* A good starting place to put the app mixin is `fleaker.testing`.
* A good composable app mixin to base off of would be:
    ```python
    class TestEnabledApp(BaseApplication):
        """In here, add the proper test_client_class attr, either on the class
        directly, or via the `__init__` method, or even a post create hook.

        Any other methods or ways to customize this that you can think of are
        highly encouraged!
        """
    ```
* Make some tests for this. A good sample test would be to define a custom application that extends the mixin directly, and make sure that all the relevant `test_client.get|post|put` methods accept the kwarg properly and work as expected. To test this, I would make a route on my custom application that requires JSON and just returns what it was given. The tests would then ensure that the response is roughly equal to the stringified testing dict.

**Comment by eligundry** [comment]
This was accomplished by #38.
